In [2]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

In [3]:
import numpy as np
import matplotlib.pyplot as plt

## Euclid's Algorithm

In [4]:
def euclid_gcd(a, b): 
    """
    """
    while b > 0:
        print(a, b)
        r = a % b
        a = b
        b = r
    
    return a

In [5]:
dir(euclid_gcd)

['__annotations__',
 '__call__',
 '__class__',
 '__closure__',
 '__code__',
 '__defaults__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__get__',
 '__getattribute__',
 '__globals__',
 '__gt__',
 '__hash__',
 '__init__',
 '__kwdefaults__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__']

In [6]:
def euclid_gcd(a, b): 
    """
    """
    while b > 0:
        print(a, b)
        r = a % b
        a = b
        b = r
    
    return a

In [7]:
print(euclid_gcd(25, 14))

25 14
14 11
11 3
3 2
2 1
1


In [8]:
print(euclid_gcd(0, 0))

0


In [9]:
def euclid_gcd(a, b): 
    """
    """
    while b > 0:
        a, b = b, a % b
        
    return a

In [10]:
print(euclid_gcd(1234, 0))

print(euclid_gcd(0, 1234))

print(euclid_gcd(1234, -143))

print(euclid_gcd(-1234, 143))

print(euclid_gcd(0, 0))

1234
1234
1234
1
0


In [11]:
def euclid_gcd(a, b): 
    """
    """
    assert a > 0 and b > 0, "both arguments must be positive"
    
    while b > 0:
        a, b = b, a % b
    
    return a

In [12]:
print(euclid_gcd(1234, 143))

print(euclid_gcd(1234*143, 143**2))

1
143


In [13]:
print(euclid_gcd(1234, -143))

AssertionError: both arguments must be positive

In [14]:
#dir(euclid_gcd)
print(euclid_gcd)

<function euclid_gcd at 0x000001CA67CF6D90>


## Giving Change

In [17]:
def change(c): 
    assert c >= 0, "change for positive amounts only"

    l_coin_values = [1, 2, 5, 10, 20, 50, 100, 200, 500, \
                     1000, 2000, 5000, 10000]
    d_change = {}
    
    for coin in sorted(l_coin_values)[ : : -1]:
        d_change[ coin ] = c // coin
        c = c % coin

    return d_change    

In [19]:
euros = 5.67
print("changing %.2f euros:" % euros)
d_change = change( int(100*euros) )

l_coin_values = [1, 2, 5, 10, 20, 50, 100, 200, 500, \
                     1000, 2000, 5000, 10000]
    
for coin in sorted(l_coin_values)[ : : -1]:
    if d_change[coin] > 0:
        print("\tcoins of value %d:\t%d" % (coin, d_change[coin]))

changing 5.67 euros:
	coins of value 500:	1
	coins of value 50:	1
	coins of value 10:	1
	coins of value 5:	1
	coins of value 2:	1


## The Traveling Salesman Problem

In [20]:
def greedy_tsp_circuit(num_cities=4):
    """First version, generating a random  matrix.
    """
    dist_m = np.random.randint(0, 200, (num_cities, num_cities) )
    dist_m = (dist_m + dist_m.T) // 2
    
    dist_m = dist_m - np.diag( np.diag(dist_m) )
    print("distance matrix:\n", dist_m)
    
    circuit = [0]
    for city in range(1, num_cities):
        options = list( np.argsort( dist_m[circuit[-1]]) )[1 : ]
        for city in options:
            if city not in circuit:
                circuit.append(city)
                break
                
    return circuit

In [24]:
circuit = greedy_tsp_circuit(4)
print("\n", circuit + [ circuit[0] ])

distance matrix:
 [[  0  91  75 142]
 [ 91   0 170 106]
 [ 75 170   0  14]
 [142 106  14   0]]

 [0, 2, 3, 1, 0]


In [36]:
def greedy_tsp_circuit(dist_m, node_ini=0):
    """Better version, receiving a distance matrix.
    """
    num_cities = dist_m.shape[0]
    assert num_cities == dist_m.shape[1] and node_ini in range(num_cities), \
           "matrix not square or invalid initial node"
           
    circuit = [node_ini]
    while len(circuit) < num_cities:
        # sort cities in ascending distance from last visited
        options = list( np.argsort( dist_m[circuit[-1]]) )[ : ]
        
        # add first city not visited in sorted list 
        for city in options:
            if city not in circuit:
                circuit.append(city)
                break
    
    return circuit + [node_ini]

In [37]:
dist_b_m_s_v = np.array([
[0, 624, 995, 350], 
[624, 0, 506, 357],
[995, 506, 0, 653],
[350, 357, 653, 0]])

circuit = greedy_tsp_circuit(dist_b_m_s_v)

d_cities = {0:'Madrid', 1:'Barcelona', 2:'Sevilla', 3:'Valencia'}

for c in circuit:
    print(d_cities[c])    

Madrid
Valencia
Barcelona
Sevilla
Madrid


## The Towers of Hanoi

In [ ]:
def hanoi(n_disks, a=1, b=2, c=3):
    """
    """
    assert n_disks > 0, "n_disks at least 1"
    
    if n_disks == 1:
        print("move disk from %d to %d" % (a, b))
    else:
        hanoi(n_disks - 1, a, c, b)
        print("move disk from %d to %d" % (a, b))
        hanoi(n_disks - 1, c, b, a)

In [ ]:
hanoi(3)

In [5]:
def hanoi(n_disks, a=1, b=2, c=3, contar=False):
    """
    """
    assert n_disks > 0, "n_disks at least 1"
    
    if n_disks == 1:
        if not contar:
            print("move disk from %d to %d" % (a, b))
        else:
            return 1
    else:
        num_moves = hanoi(n_disks - 1, a, c, b, contar)
        if not contar:
            print("move disk from %d to %d" % (a, b))
        hanoi(n_disks - 1, c, b, a, contar)
        
        if contar:
            return 2*num_moves + 1

In [9]:
hanoi(5)

move disk from 1 to 2
move disk from 1 to 3
move disk from 2 to 3
move disk from 1 to 2
move disk from 3 to 1
move disk from 3 to 2
move disk from 1 to 2
move disk from 1 to 3
move disk from 2 to 3
move disk from 2 to 1
move disk from 3 to 1
move disk from 2 to 3
move disk from 1 to 2
move disk from 1 to 3
move disk from 2 to 3
move disk from 1 to 2
move disk from 3 to 1
move disk from 3 to 2
move disk from 1 to 2
move disk from 3 to 1
move disk from 2 to 3
move disk from 2 to 1
move disk from 3 to 1
move disk from 3 to 2
move disk from 1 to 2
move disk from 1 to 3
move disk from 2 to 3
move disk from 1 to 2
move disk from 3 to 1
move disk from 3 to 2
move disk from 1 to 2


In [8]:
for num_disks in range(1, 11):
    print("num_disks: %d\tnum_moves: %d" % (num_disks, hanoi(num_disks, contar=True)))

num_disks: 1	num_moves: 1
num_disks: 2	num_moves: 3
num_disks: 3	num_moves: 7
num_disks: 4	num_moves: 15
num_disks: 5	num_moves: 31
num_disks: 6	num_moves: 63
num_disks: 7	num_moves: 127
num_disks: 8	num_moves: 255
num_disks: 9	num_moves: 511
num_disks: 10	num_moves: 1023


## Sorting

In [50]:
def merge_sort_0(l_ints):
    n = len(l_ints)
    
    if n == 1:
        return l_ints
        
    elif n > 1:
        m = (n-1)//2
        l_left  = merge_sort_0(l_ints[ : m+1])
        l_right = merge_sort_0(l_ints[m+1: ])
            
        return sorted(l_left + l_right)

In [51]:
l_ints = [1437, 224, 73, 95, 42]

merge_sort_0(l_ints)

[42, 73, 95, 224, 1437]

In [52]:
def combine(l_left, l_right):
    """
    """
    l_combined = []
    i_left = i_right= 0
    
    while i_left < len(l_left) and i_right < len(l_right):
        if l_left[i_left] <= l_right[i_right]:
            l_combined.append(l_left[i_left])
            i_left += 1
        else:
            l_combined.append(l_right[i_right])
            i_right += 1
    
    if i_left < len(l_left):
        l_combined += l_left[i_left : ]
    else:
        l_combined += l_right[i_right : ]
    
    return l_combined


def merge_sort(l_ints):
    """
    """
    n = len(l_ints)
    
    if n == 1:
        return l_ints
        
    elif n > 1:
        m = (n+1)//2
        l_left  = merge_sort(l_ints[ : m])
        l_right = merge_sort(l_ints[m: ])
            
        return combine(l_left, l_right)

In [53]:
l_ints = [1437, 224, 73, 95, 42, 673, 59, 13, 2345]

merge_sort_0(l_ints)

[13, 42, 59, 73, 95, 224, 673, 1437, 2345]

## Matrix Multiplication

In [54]:
def matrix_multiplication(m_1, m_2):
    """
    """
    n_rows, n_interm, n_columns = \
        m_1.shape[0], m_2.shape[0], m_2.shape[1]
    
    m_product = np.zeros( (n_rows, n_columns) )
    
    for p in range(n_rows):
        for q in range(n_columns):
            for r in range(n_interm):
                m_product[p, q] += m_1[p, r] * m_2[r, q]
                
    return m_product

In [55]:
m_1 = np.ones( (4, 4) )
m_2 = np.eye(4)

print( matrix_multiplication(m_1, m_1) )

print('\n',  matrix_multiplication(m_1, m_2) )

print('\n',  matrix_multiplication(m_2, m_2) )

[[ 4.  4.  4.  4.]
 [ 4.  4.  4.  4.]
 [ 4.  4.  4.  4.]
 [ 4.  4.  4.  4.]]

 [[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]

 [[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


## Linear Search

In [56]:
def linear_search(key, l_ints):
    for i, val in enumerate(l_ints):
        if l_ints[i] == key:
            return i
    
    return None

In [68]:
l_ints = list(range(100))

l_keys = [100, 2, 6, 9, -4, 2.5]

for key in l_keys:
    key_pos = linear_search(key, l_ints)
    if key_pos:
        print('\npos of key %d: %d' % (key, key_pos))
    else:
        if isinstance(key, int):
            print('\nkey %d not in list' % key)
        elif isinstance(key, float):
            print('\nkey %.2f not in list' % key)


key 100 not in list

pos of key 2: 2

pos of key 6: 6

pos of key 9: 9

key -4 not in list

key 2.50 not in list


## Basic Timing

In [58]:
a = np.ones((50, 50))
b = np.eye(50)

%timeit matrix_multiplication(a, b)

1 loop, best of 3: 475 ms per loop


In [59]:
a = np.ones((50*5, 50*5))
b = np.eye(50*5)

%timeit matrix_multiplication(a, b)

1 loop, best of 3: 1min 1s per loop


In [60]:
a = np.ones((50*5, 50*5))
b = np.eye(50*5)

%timeit a.dot(b)

The slowest run took 147.06 times longer than the fastest. This could mean that an intermediate result is being cached.
1 loop, best of 3: 5.8 ms per loop
